apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: sqlserver
  namespace: "{{ .Values.infrastructure.namespace }}"
data:
  sa_user: {{ .Values.infrastructure.username | b64enc }}
  sa_password: {{ .Values.infrastructure.password | b64enc }}